Update requirements_docs.txt
Based on this error message from the CI build:

```
Run sphinx-build -n -j auto -b html -d build/doctrees docs build/html
  sphinx-build -n -j auto -b html -d build/doctrees docs build/html
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib
Running Sphinx v4.5.0

Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
Error: Process completed with exit code 2.
```

bump sphinx to >= 5 (>4 only got us to 4.5).

Signed-off-by: Michael Tiemann <72577720+MichaelTiemannOSC@users.noreply.github.com>