Fix dimensionality error message
Fixes great DimensionalityError that occurs when you pow with a single
value quantity.
DimensionalityError: Cannot convert from 'dimensionless' to
'dimensionless'